### ISSUE TITLE
app-accordion gives unhandled errors in Oqtane 6: TypeError: Cannot read properties of null (reading 'querySelectorAll')

### ISSUE THREAD

**Issue by patrickjlee** [2sic/app-accordion-bootstrap3#24]
I tried yesterday twice to use the accordion app in Oqtane, but each time I got unhandled errors:

TypeError: Cannot read properties of null (reading 'querySelectorAll')
  Message=
  Source=
  StackTrace:
  at t.initAccordionBs5 [as initBs5] (http://localhost:44357/app/Accordion4/assets/bs5/dist/scripts.min.js:1:3091)
    at http://localhost:44357/Modules/ToSic.Sxc.Oqtane/dist/turnOn/turn-on.js:1:4452

![image](https://github.com/user-attachments/assets/ed6fbc30-3600-423e-b686-871f59c63c6d)

I got this error even on pages without the accordion.  So I had to delete the page with the accordion.

Any idea how to fix this please?

**Comment by iJungleboy** [comment]
Thanks for reporting this.

@ropalko could you look into this?

**Comment by ropalko** [comment]
Thank you for reporting the error to us. I was able to reproduce the error. It only appears in certain Oqtane settings.
![image](https://github.com/user-attachments/assets/3f4f6a98-f704-4fcf-9d44-71796ea1dcf3)

I have made a new release of the app. To fix the error, you could adjust two files in your app instead of reinstalling it.
[scripts.min.js](https://github.com/2sic/app-accordion/blob/master/bs5/dist/scripts.min.js)
[scripts.min.js.map](https://github.com/2sic/app-accordion/blob/master/bs5/dist/scripts.min.js.map)

These are located under /bs5/dist

**Comment by patrickjlee** [comment]
Thanks! That has solved my original problem.  But I now get a new one. When editing (or sometimes even just clicking on a 2nd accordion app on a new test page) , it seems to treat it as a hyperlink with names like localhost:44357/#a-2985 which takes me away from the page with the accordion on and to the site's home page...

**Comment by iJungleboy** [comment]
@patrickjlee pls create a new issue for this, so we can discuss

**Comment by patrickjlee** [comment]
Thanks @iJungleboy , new issue created https://github.com/2sic/app-accordion/issues/25
